# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bfdf753394fcdf9910d21e26ff86c52ba2d035098c5975a2ff6f4e59ed8251fda012a5c4b8af9c7bc578dd23fbdecd8f8395bdcde2c6d6a1b5f418fe35d1d46

test:
  secret_key_base: e30c780938cf108a22609444c40d816d8570ea75ffde4e4415117ab260b129ca869ef324eca875575b3c8c640b59f4202bc9cf18327e0aff451ee61bf41797f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
